<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="folding_table">
  <xacro:property name="filename" value="$(find blocks)/models/table.yaml"/>
  <xacro:property name="model" value="${load_yaml(filename)}"/>

  <xacro:property name="body_l" value="${model['length']}"/>
  <xacro:property name="body_w" value="${model['width']}"/>
  <xacro:property name="body_h" value="${model['height']}"/>
  
  <xacro:property name="color" default="Wood" />
  <!--Gazebo colors: http://wiki.ros.org/simulator_gazebo/Tutorials/ListOfMaterials -->
  <link name="table">
    <inertial>
      <origin xyz="${body_l/2} ${body_w/2} ${body_h/2}" />
      <mass value="0.5" />
   <inertia  ixx="0.5" ixy="0.0"  ixz="0.0"  iyy="0.5"  iyz="0.0"  izz="0.5" />
    </inertial>
    <visual>
      <origin xyz="${body_l/2} ${body_w/2} ${body_h/2}" />
      <geometry>
        <box size="${body_l} ${body_w} ${body_h}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="${body_l/2} ${body_w/2} ${body_h/2}" />
      <geometry>
        <box size="${body_l} ${body_w} ${body_h}" />
      </geometry>
    </collision>
  </link>
  
  <gazebo reference="table">
     <material>Gazebo/${color}</material>
     <mu1>1000</mu1>
     <mu2>1000</mu2>
  </gazebo>
</robot>
