<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="block">
  <xacro:property name="body_l" value="0.0635"/>
  <xacro:property name="body_w" value="0.03175"/>
  <xacro:property name="body_h" value="0.0127"/>
  
  <xacro:property name="color" default="Green" />
  <link name="${color}_block">
    <inertial>
      <origin xyz="${body_l/2} ${body_w/2} ${body_h/2}" />
      <mass value="0.5" />
   <inertia  ixx="0.5" ixy="0.0"  ixz="0.0"  iyy="0.5"  iyz="0.0"  izz="0.5" />
    </inertial>
    <visual>
      <origin xyz="${body_l/2} ${body_w/2} ${body_h/2}" />
      <geometry>
        <box size="${body_l} ${body_w} ${body_h}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="${body_l/2} ${body_w/2} ${body_h/2}" />
      <geometry>
        <box size="${body_l} ${body_w} ${body_h}" />
      </geometry>
    </collision>
  </link>
  
  <gazebo reference="${color}_block">
     <material>Gazebo/${color}</material>
     <mu1>1000</mu1>
     <mu2>1000</mu2>
  </gazebo>
</robot>
